### ISSUE TITLE
Remove the database and the cache from the core ✨

### ISSUE THREAD

**Issue by yezz123** [yezz123/authx#100]
### Discussed in https://github.com/yezz123/AuthX/discussions/96

<div type='discussions-op-text'>

<sup>Originally posted by **AbderrahimSoubaiElidrissi** October 26, 2021</sup>
Hello 

I suggest removing database ORM and the cache from the core and adding them as plugins</div>

Working on Adding multiple database providers or ORMs and using them as pluggings.

**Comment by MojixCoder** [comment]
I agree with that, as the name of package is authx. I think it's better to have authentication related stuff in the core. it makes the package simple and smaller so it's easier to be maintained and be improved.

**Comment by yezz123** [comment]
> I agree with that, as the name of the package is authx. I think it's better to have authentication-related stuff in the core. it makes the package simple and smaller so it's easier to be maintained and be improved.

Yes, I agree with you, I was thinking only to add the databases or cache provider as optional add-ons, that why I work first with a NoSQL database(MongoDB) & Redis cache, but I think its better to let it optional and add an ORM for SQL's databases.
You could check this branch https://github.com/webstack/AuthX/commit/680a9ceb264c35a9839e57debc634df3ac48ee6b
