### ISSUE TITLE
datetime field invalid format string

### ISSUE THREAD

**Issue by alecvinent** [yezz123/authx#121]
I'm getting "Invalid format string" with datetime field. After debug, I've isolated the error at _UserPrivateInfo_ class, _set_format_ method. Sample value:

`2021-11-06 15:43:18.021855 Invalid format string`

## Configuration

- Python version : 3.8
- FastAPI version : 0.70.0
- AuthX version : 0.1.1

**Comment by yezz123** [comment]
Hello @alecvinent 👋🏻 , i will try multiple fixes during this day by changing the Modulo name #124 #125 also i will look on your case about the invalid format string 🚀

**Comment by yezz123** [comment]
Maybe we could right now transfer it to a discussion while I got to debug, and I didn't get any issue relate to `datetime` or `time_delta`
