### ISSUE TITLE
Update PyJwt to last version and fix `.decode` issue ✨

### ISSUE THREAD

**Issue by yezz123** [yezz123/authx#148]
I just merge the improvement here in  the dev branch under this commit https://github.com/yezz123/authx/commit/fd06930af68a9e658bbf8fac279a8b6c322bca68

**Comment by MojixCoder** [comment]
did you solve the issue? I think i know the problem

**Comment by yezz123** [comment]
I'm not familiar with that version of pyJWT that's gonna help if you open a PR @MojixCoder or you guide me to solve it

**Comment by MojixCoder** [comment]
I opened a [PR](https://github.com/yezz123/authx/pull/151) for that
