### ISSUE TITLE
Sorry, the documentation and examples are really bad, none of them can run through

### ISSUE THREAD

**Issue by InfernalAzazel** [yezz123/authx#228]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to AuthX but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to AuthX but to [FastAPI](https://github.com/tiangolo/fastapi).

### Example Code

```python
from urllib.parse import quote_plus

from authx import MongoDBBackend

from fastapi import APIRouter, Depends, FastAPI
from starlette.config import Config

from authx import Authentication, User

app = FastAPI(
    title="AuthX",
    description="AuthX is a simple authentication system for fastapi.",
    version="0.1.0",
)

config = Config(".env")
auth = Authentication(
    database_backend=MongoDBBackend(database_name='test'),
    debug=config("DEBUG", default=False, cast=bool),
    base_url=config("BASE_URL", default="mongodb://%s:%s@%s" \
                                        % (quote_plus('spb0'),  # user
                                           quote_plus('dcaGRzkJp'),  # password
                                           '127.0.0.1')),
    site=config("SITE", default="authx"),
    callbacks=[],
    access_cookie_name=config("ACCESS_COOKIE_NAME", default="access_token"),
    refresh_cookie_name=config("REFRESH_COOKIE_NAME", default="refresh_token"),
    private_key=config("PRIVATE_KEY", default="private_key"),
    public_key=config("PUBLIC_KEY", default="public_key"),
    access_expiration=config("ACCESS_EXPIRATION", default=3600),
    refresh_expiration=config("REFRESH_EXPIRATION", default=86400),
    smtp_username=config("SMTP_USERNAME", default="username"),
    smtp_password=config("SMTP_PASSWORD", default="password"),
    smtp_host=config("SMTP_HOST", default="smtp.gmail.com"),
    smtp_tls=config("SMTP_TLS", default=True),
    display_name=config("DISPLAY_NAME", default="AuthX"),
    recaptcha_secret=config("RECAPTCHA_SECRET", default="secret"),
    social_providers=[],
    social_creds=None,
)
router = APIRouter()

app.include_router(auth.auth_router, prefix="/api/auth", tags=["auth"])
app.include_router(auth.password_router, prefix="/api/password", tags=["password"])
app.include_router(auth.admin_router, prefix="/api/admin", tags=["admin"])
app.include_router(auth.search_router, prefix="/api/search", tags=["search"])


# Set Anonymous User
@router.get("/anonym")
def anonym_test(user: User = Depends(auth.get_user)):
    pass


# Set Authenticated User
@router.get("/user")
def user_test(user: User = Depends(auth.get_authenticated_user)):
    pass


# Set Admin User
@router.get("/admin", dependencies=[Depends(auth.admin_required)])
def admin_test():
    pass
```

### Description

Refer to the official documentation, including code examples, none of them can run

### Operating System

Linux

### Operating System Details

Ubantu 20 tls

### FastAPI Version

0.70.1

### Python Version

Python 3.8.10

### Additional Context

error:
/usr/bin/python3.8 /home/Documents/code/my/a/main.py
Traceback (most recent call last):
  File "/home/Documents/code/my/a/main.py", line 3, in <module>
    from authx import Authentication, MongoDBBackend
  File "/home/.local/lib/python3.8/site-packages/authx/__init__.py", line 5, in <module>
    from authx.api import UsersRepo as UsersRepo
  File "/home/.local/lib/python3.8/site-packages/authx/api/__init__.py", line 1, in <module>
    from authx.api.users import UsersRepo
  File "/home/.local/lib/python3.8/site-packages/authx/api/users.py", line 18, in <module>
    from authx.database import BaseDBBackend
  File "/home/.local/lib/python3.8/site-packages/authx/database/__init__.py", line 1, in <module>
    from authx.database.base import BaseDBBackend
  File "/home/.local/lib/python3.8/site-packages/authx/database/base.py", line 5, in <module>
    class BaseDBBackend:
  File "/home/.local/lib/python3.8/site-packages/authx/database/base.py", line 39, in BaseDBBackend
    async def search(self, f: dict, p: int, size: int) -> tuple[dict, int]:
TypeError: 'type' object is not subscriptable

进程已结束,退出代码1

**Comment by yezz123** [comment]
hey @InfernalAzazel I'm working on bootstrapping the library and release the clean version soon, I know i will face much issues in the upcoming months that's why i will try to work fast in this part 👍🏻

**Comment by InfernalAzazel** [comment]
@yezz123 Come on, I am very optimistic about this project. I hope the configuration can be simpler. There are too many configurations in the testing phase. You can configure it according to your needs.
