### ISSUE TITLE
There is ambiguous loop in resolve_user for social auth

### ISSUE THREAD

**Issue by iftenet** [yezz123/authx#265]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to AuthX but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to AuthX but to [FastAPI](https://github.com/tiangolo/fastapi).

### Example Code

```python
while True: 
     resolved_username = f"{username}{postfix}" 
     existing_username = await self._repo.get_by_username(resolved_username) 
     if not existing_username: 
         break
```

### Description

Could you please some one check this below code base where loop is indicating something ambiguous .

https://github.com/yezz123/authx/blob/eefba52c32222b88171e4b300d025937496d7e1f/authx/services/social.py#L127-L131

### Operating System

macOS

### FastAPI Version

0.85.0

### Python Version

3.9

**Comment by iftenet** [comment]
I believe some thing like below could solve this loop issue.

```
            resolved_username = username
            while True:
                postfix = str(i) if i > 0 else ""
                resolved_username = f"{username}{postfix}"
                existing_username = await self._repo.get_by_username(resolved_username)
                if not existing_username:
                    break
                i = i+1
```

**Comment by yezz123** [comment]
Hello, @iftenet I didn't notice that loop, but I see it can be fixed as you proposed, want to contribute and open a Pull request?

**Comment by iftenet** [comment]
> Hello, @iftenet I didn't notice that loop, but I see it can be fixed as you proposed, want to contribute and open a Pull request?

I will be glad if you give me the opportunity to contribute.

**Comment by iftenet** [comment]
@yezz123 I am going to create a PR but seems I have no permission to push.

**`ERROR: Permission to yezz123/authx.git denied to iftenet.`**

**Comment by yezz123** [comment]
> @yezz123 I am going to create a PR but seems I have no permission to push.
> 
> 
> 
> **`ERROR: Permission to yezz123/authx.git denied to iftenet.`**

You can fork the project and try to made your changes in your fork you will find it in this way, iftenet/authx.git then a yellow head with a button create PR
