### ISSUE TITLE
📝 Followup with documentation - Internal Feature

### ISSUE THREAD

**Issue by yezz123** [yezz123/authx#460]
Introducing AuthX V1.0.0, our redesigned authentication system. This version incorporates numerous fresh functionalities and improvements aimed at enhancing security, usability, and performance.

## Core Functionality:

- JWT encoding/decoding for application authentication
- Automatic detection of JWTs in requests:
    - JWTs in headers
    - JWTs in cookies
    - JWTs in query strings
    - JWTs in JSON bodies
- Implicit/explicit token refresh mechanism
- Tracking the freshness state of tokens
- Route protection:
    - Protection based on token type (access/refresh)
    - Protection based on token freshness
    - Partial route protection
- Handling custom user logic for revoked token validation
- Handling custom logic for token recipient retrieval (ORM, pydantic serialization...)
- Providing FastAPI-compliant dependency injection API
- Automatic error handling

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/yezz123) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/yezz123/authx/issues/460">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/yezz123/authx/issues/460/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/yezz123/authx/issues/460/pledge.svg">
</picture>
</a>

**Comment by dearkafka** [comment]
nice features! looking forward to it!
