### ISSUE TITLE
cannot import 'ProfilerMiddleware' from 'authx'

### ISSUE THREAD

**Issue by TMGboy** [yezz123/authx#658]
ImportError: cannot import name 'ProfilerMiddleware' from 'authx' (/usr/local/lib/python3.9/dist-packages/authx/__init__.py)

**Comment by yezz123** [comment]
Hey @TMGboy 👋🏻 

`ProfilerMiddleware` is migrated to authx-extra you can use it like this:

```bash
pip install authx-extra[profiler]
```

- then add this:

```py
from fastapi import FastAPI
from authx_extra.profiler import ProfilerMiddleware

app = FastAPI()

app.add_middleware(ProfilerMiddleware)
```
