### ISSUE TITLE
🐛  Error: Missing `Audience` & `Issuer` in the verify token function 

### ISSUE THREAD

**Issue by jmarianom** [yezz123/authx#683]
Greetings!

I have a problem with AuthX, it raises a exception with the error "Invalid audience" when I set the field "aud" in the token.

Valid token with "aud" (encoded with "HS256" and the same "secret key" of the example): **eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjE4ZTRlOWVlLWQ3ZmQtNDQ4ZS04ZDc3LTQ4MTQ1MmVkNGViNSIsInR5cGUiOiJhY2Nlc3MiLCJmcmVzaCI6ZmFsc2UsImNzcmYiOiIiLCJpYXQiOjE3MjgzMjM1ODMsImV4cCI6MTczNTU4MTE4My4wMTE5MTksImF1ZCI6InRlc3RBcHAifQ.j_RA19QwFGhMQrVJ7dnrCm4D9RoOEVrgng_Vk0a9i5E**

```
from fastapi import FastAPI, Depends, HTTPException
from authx import AuthX, AuthXConfig, RequestToken

app = FastAPI()

config = AuthXConfig(
     JWT_SECRET_KEY = "SECRET_KEY",
     JWT_ENCODE_AUDIENCE="testApp",
     JWT_DECODE_AUDIENCE="testApp"
)

auth = AuthX(config=config)
auth.handle_errors(app)        

@app.get("/protected", dependencies=[Depends(auth.get_token_from_request)])
def get_protected(token: RequestToken = Depends()):
     try:
          auth.verify_token(token=token)
          return {"message": "Hello world !"}
     except Exception as e:
          raise HTTPException(401, detail={"message": str(e)}) from e
```

When I introduce the token raises the exception. According to PyJWT, the problem seems to be due to the missing parameter "audience" when invoking the "decode" method https://github.com/jpadilla/pyjwt/issues/120

Sorry for my English, I'm Spanish.

**Comment by yezz123** [comment]
Hello @jmarianom I checked the issue and its seems coming from the verify Function talking about here: https://github.com/yezz123/authx/blob/fcce4bdaefcbf27a165181309faf93cded005a16/authx/main.py#L383-L390

We should add :

```py
            audience=self.config.JWT_DECODE_AUDIENCE,
            issuer=self.config.JWT_DECODE_ISSUER,
```

and its will work good with this example you provide:

```py
from fastapi import Depends, FastAPI, HTTPException

from authx import AuthX, AuthXConfig, RequestToken

app = FastAPI()

config = AuthXConfig(
     JWT_SECRET_KEY = "SECRET_KEY",
     JWT_ENCODE_AUDIENCE="testApp",
     JWT_DECODE_AUDIENCE="testApp"
)

auth = AuthX(config=config)
auth.handle_errors(app)

@app.get("/")
def get_root():
     return {"message": "Hello world !"}


@app.get("/protected", dependencies=[Depends(auth.get_token_from_request)])
def get_protected(token: RequestToken = Depends()):  # noqa: B008
     try:
          auth.verify_token(token=token)
          return {"message": "Hello world !"}
     except Exception as e:
          raise HTTPException(401, detail={"message": str(e)}) from e

if __name__ == "__main__":
     import uvicorn
     uvicorn.run(app, host="0.0.0.0", port=8000)
```

![Screenshot 2024-10-15 at 19 19 33](https://github.com/user-attachments/assets/e0738307-1cbb-4878-8a38-043477dcdc86)

![Screenshot 2024-10-15 at 19 19 49](https://github.com/user-attachments/assets/5fb127df-8811-4630-8103-f82d7bc75c68)


I will fix it and provide it in the upcoming release 🐛 

Thanks for catching this 🚀
